steps:

# Docker Build command
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/qwiklabs-gcp-01-36238c49377d/gke-repo/quickstart-image', './app1' ]
  id: 'Build Docker Image'

  # images:
  # - 'us-central1-docker.pkg.dev/qwiklabs-gcp-01-36238c49377d/gke-repo/quickstart-image'

# Docker Push Command
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/qwiklabs-gcp-01-36238c49377d/gke-repo/quickstart-image' ]
  id: 'Push Docker Image'

# Docker Build command
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/qwiklabs-gcp-01-36238c49377d/gke-repo/flask-image', './app2' ]
  id: 'Build Docker Image2'

  # images:
  # - 'us-central1-docker.pkg.dev/qwiklabs-gcp-01-36238c49377d/gke-repo/quickstart-image'

# Docker Push Command
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/qwiklabs-gcp-01-36238c49377d/gke-repo/flask-image' ]
  id: 'Push Docker Image2'

# Creating Cloud Deploy Pipeline and then creating releases for app1 and app2
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file cloud-deploy/pipeline.yaml --region=us-central1
    gcloud deploy apply --file cloud-deploy/dev.yaml --region=us-central1
    gcloud deploy apply --file cloud-deploy/prod.yaml --region=us-central1

    # gcloud deploy releases create 'app1-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml

    gcloud deploy releases create 'app1-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --from-k8s-manifest=./kubernetes/*
    gcloud deploy releases create 'app2-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --from-k8s-manifest=./kubernetes/*


options:
  logging: CLOUD_LOGGING_ONLY
