apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/qwiklabs-gcp-02-ab5f4917d21f/locations/us-central1/clusters/autopilot-cluster-1

