apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/qwiklabs-gcp-03-1b3e99931cdc/locations/us-east4/clusters/autopilot-cluster-1

