apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/qwiklabs-gcp-01-36238c49377d/locations/us-central1/clusters/autopilot-cluster-1

