apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/qwiklabs-gcp-01-36238c49377d/locations/us-central1/clusters/autopilot-cluster-2-prod

