apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1-container
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-03-1b3e99931cdc/gke-artifact-repo/app1-image:v01
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/persistent_data
          mountPropagation: HostToContainer
          name: app1-storage
      volumes:
      - name: app1-storage
        persistentVolumeClaim:
          claimName: my-app-pvc-dynamic

---

# --- pvc-dynamic.yaml ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-pvc-dynamic # Name of your storage request
spec:
  # Use a StorageClass available in your GKE cluster
  # 'standard-rwo' is a default GKE class using standard GCE PDs
  storageClassName: standard-rwo
  accessModes:
    # ReadWriteOnce allows the volume to be mounted as read-write by a single node
    - ReadWriteOnce
  resources:
    requests:
      # Request 10 GiB of storage
      storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer